# Generated by Django 3.1.4 on 2020-12-26 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201226_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voting'),
        ),
        migrations.AlterField(
            model_name='favouritevoting',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favouritevoting',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voting'),
        ),
        migrations.AlterField(
            model_name='votefact',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votefact',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.votevariant'),
        ),
        migrations.AlterField(
            model_name='votevariant',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voting'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
