# Generated by Django 3.1.4 on 2020-12-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201226_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voting',
            options={'ordering': ['-finished']},
        ),
    ]
