# Generated by Django 3.1.5 on 2021-01-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201226_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='votefact',
            name='voting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.voting'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VotingImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voting')),
            ],
        ),
    ]
