# Generated by Django 3.1.5 on 2021-01-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201226_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voting')),
            ],
        ),
    ]
